spring.application.name=lojavirtual

spring.sql.init.mode=always
# Desativa a criacao automatica do Hibernate para usar seus arquivos .sql
spring.jpa.hibernate.ddl-auto=none

# Nostra os comandos SQL no console para facilitar o desenvolvimento
spring.jpa.show-sql=true

# --- (H2 em Memoria) ---
spring.sql.init.platform=h2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true


# --- (MS SQL Server) ---
# Substitua 'localhost', 'nome_banco',  pelos seus dados
#spring.sql.init.platform=sqlserver
#spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=lojavirtual;integratedSecurity=true;encrypt=true;trustServerCertificate=true
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.web.error.include-stacktrace=never